name: Concurrency Testing
on: workflow_dispatch 

# Создаем id для workflow, чтобы GitHub определял защенные wokflow по нему
# Придумываем id сами
concurrency:  
    group: concurrency-testing  
    # Отменяет все предыдущие workflow, и запускает последний в очереди 
    cancel-in-progress: true

jobs:
    test-timeout:
        runs-on: ubuntu-latest
        # Задаем одну минуту на выполнение всего job'а
        steps:
            - name: Some step
              timeout-minutes: 1
            # Спим 200 сек
              run: sleep 50
            