name: Eighth Workflow 

on:
  workflow_dispatch: # Запускается в ручную
    inputs:
        titleCustom:
            description: Type the Title
            type: string 
            required: true
            default: "Hello world!"
jobs: 
    first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Event vars
        # Используем input
          run: | 
            echo "Title: ${{ inputs.titleCustom }}" 