name: Eighth Workflow 

on:
  workflow_dispatch: # Запускается в ручную
    inputs:
        titleCustom:
            description: Type the Title
            type: string 
            required: true
            default: "Hello world!"
        selectCustom:
            description: Select Value 
            type: choice
            required: true 
            options:
                - Value1
                - Value2
                - Value3
            default: "Value 2"
        checkCustom:
            description: Checkbox
            type: boolean 
            required: false 
jobs: 
    first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Event vars
        # Используем input
          run: | 
            echo "Title: ${{ inputs.titleCustom }}"
            echo "Select: ${{ inputs.selectCustom}}"
            echo "Check: ${{ inputs.checkCustom }}" 