name: Fifth Workflow (name of workflow)
 

on: 
  issues:
    types: [edited, deleted]
  pull_request:
    types: [assigned, closed]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Event vars
            # GITHUB_SHA - от какого коммита запускается workflow 
            # GITHUB_REF - на какой ветке этот коммит
              run: | 
                echo $GITHUB_SHA 
                echo $GITHUB_REF