name: Sixteenth Workflow 
run-name: My Sixteenth Workflow 

on: push 

jobs:
    testing-matrix-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12, 14, 18]
        steps:
            - name: Write version 
              run: echo '${{matrix.node-version}}'