name: Third Workflow 
on: push 

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Command in Multiline
             # pwd - Рабочий каталог ls -a - файлы в рабочем каталоге
              run: |
                pwd
                ls -a

