name: Twelve Workflow

on: [push]

jobs:
    run-first-commond:
        runs-on: ubuntu-latest 
        steps:
            - name: Our Vars & Secrets
              run: |
               echo '${{vars.STATUS}}'
               echo '${{secrets.PASSWORD}}'
